# roles/github-runner/tasks/install_runner.yml

- name: Download GitHub Runner binary
  get_url:
    url: "https://github.com/actions/runner/releases/download/v2.317.0/actions-runner-linux-x64-2.317.0.tar.gz"
    dest: "{{ runner_dir_base }}/{{ item }}/actions-runner.tar.gz"
    mode: '0755'
  loop: "{{ runner_names }}"
  become: true

- name: Extract GitHub Runner
  unarchive:
    src: "{{ runner_dir_base }}/{{ item }}/actions-runner.tar.gz"
    dest: "{{ runner_dir_base }}/{{ item }}/"
    remote_src: yes
  loop: "{{ runner_names }}"
  become: true

- name: Configure GitHub Runner
  shell: |
    ./config.sh --url https://github.com/{{ org }} \
                --token {{ gh_token }} \
                --name {{ item }} \
                --labels {{ runner_labels[item] }} \
                --unattended
  args:
    chdir: "{{ runner_dir_base }}/{{ item }}"
  loop: "{{ runner_names }}"
  become: true

- name: Run GitHub Runner as service
  shell: ./svc.sh install && ./svc.sh start
  args:
    chdir: "{{ runner_dir_base }}/{{ item }}"
  loop: "{{ runner_names }}"
  become: true
